name: CI_prod Workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  Test:
    name: Run unit test
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    environment: main

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.PASSWORD }}
      SNOWFLAKE_DATABASE: ${{ secrets.DATABASE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.WAREHOUSE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SCHEMA }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version if needed

      - name: Install dbt
        run: pip install dbt
        shell: bash

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
        shell: bash

      - name: Install dependencies
        run: |
          pip install -r setup/requirements.txt
        shell: bash

      - name: Prepare dbt profiles
        run: |
          mkdir -p ~/.dbt
          echo 'kiff_ecommerce:' > ~/.dbt/profiles.yml
          echo '  target: dev' >> ~/.dbt/profiles.yml
          echo '  outputs:' >> ~/.dbt/profiles.yml
          echo '    dev:' >> ~/.dbt/profiles.yml
          echo '      type: snowflake' >> ~/.dbt/profiles.yml
          echo "      account: $SNOWFLAKE_ACCOUNT" >> ~/.dbt/profiles.yml
          echo "      user: $SNOWFLAKE_USER" >> ~/.dbt/profiles.yml
          echo "      password: $SNOWFLAKE_PASSWORD" >> ~/.dbt/profiles.yml
          echo "      database: $SNOWFLAKE_DATABASE" >> ~/.dbt/profiles.yml
          echo "      warehouse: $SNOWFLAKE_WAREHOUSE" >> ~/.dbt/profiles.yml
          echo "      schema: $SNOWFLAKE_SCHEMA" >> ~/.dbt/profiles.yml
        shell: bash

      - name: Run dbt deps
        run: dbt deps --profiles-dir ~/.dbt
        shell: bash

      - name: Run dbt test with kiff_ecommerce profile
        run: dbt test --profiles-dir ~/.dbt --profile kiff_ecommerce
        shell: bash

  goodbye:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Goodbye world
        run: echo "Bye World"
        shell: bash
